# Generated by Django 4.2.7 on 2026-08-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('faculty', models.CharField(choices=[('computing', 'Faculty of Computing, Library and Information Science'), ('engineering', 'Faculty of Engineering, Technology, Applied Design and Fine Art'), ('science', 'Faculty of Science'), ('education', 'Faculty of Education'), ('medicine', 'School of Medicine'), ('economics', 'Faculty of Economics and Management Sciences'), ('agriculture', 'Faculty of Agriculture and Environmental Sciences'), ('law', 'Faculty of Law'), ('arts', 'Faculty of Arts and Social Sciences'), ('languages', 'Institute of Languages'), ('tourism', 'Institute of Tourism and Hospitality'), ('other', 'Other')], max_length=40)),
                ('program', models.CharField(max_length=150)),
                ('year_of_study', models.CharField(choices=[('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_3', 'Year 3'), ('year_4', 'Year 4'), ('postgraduate', 'Postgraduate'), ('staff', 'Staff'), ('visitor', 'Visitor')], max_length=20)),
                ('student_number', models.CharField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('prefer_not', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('some', 'Some experience'), ('advanced', 'Advanced')], max_length=20)),
                ('heard_from', models.CharField(blank=True, choices=[('friend', 'Classmate or friend'), ('lecturer', 'Lecturer'), ('poster', 'Poster or campus notice'), ('social', 'WhatsApp or social media'), ('other', 'Other')], max_length=20)),
                ('code_of_conduct_agreed', models.BooleanField()),
                ('registration_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
