# Generated by Django 4.2.7 on 2026-08-27 21:55

from django.db import migrations, models
import django.db.models.deletion


def lowercase_and_dedupe_emails(apps, schema_editor):
    Registrant = apps.get_model("registrations", "Registrant")
    seen = {}
    for person in Registrant.objects.order_by("id"):
        email = (person.email or "").strip().lower()
        if not email:
            email = f"unknown{person.id}@kab.ac.ug"
        if "@" in email:
            local, domain = email.split("@", 1)
        else:
            local, domain = email, "kab.ac.ug"
        while email in seen:
            email = f"{local}+dup{person.id}@{domain}"
        seen[email] = person.id
        if person.email != email:
            person.email = email
            person.save(update_fields=["email"])


def seed_existing_members(apps, schema_editor):
    Registrant = apps.get_model("registrations", "Registrant")
    Event = apps.get_model("registrations", "Event")
    Attendance = apps.get_model("registrations", "Attendance")
    people = list(Registrant.objects.order_by("created_at", "id"))
    if not people:
        return
    first = people[0]
    event_date = first.created_at.date() if first.created_at else None
    if event_date is None:
        from django.utils import timezone

        event_date = timezone.now().date()
    event = Event.objects.create(
        name="Club registration",
        event_date=event_date,
        registration_open=False,
    )
    Attendance.objects.bulk_create(
        [Attendance(attendant=person, event=event) for person in people]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("event_date", models.DateField()),
                ("registration_open", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-event_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="registrations.registrant",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="registrations.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("attendant", "event"),
                name="unique_attendance_per_event",
            ),
        ),
        migrations.RunPython(lowercase_and_dedupe_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registrant",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RunPython(seed_existing_members, migrations.RunPython.noop),
    ]
